import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.restassured.response.Response;
import org.apache.commons.io.FileUtils;
import java.io.File;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class createDataInSmile extends utils {
    private static String jsonTemplate = getGlobalValue("jsonTemplate");

    public static void main(String[] args) throws Exception {
        //Get count of json to be generated by reading values having <> in template
//        int count = getCount(jsonTemplate);
          int count =1;
        for(int i = 0; i< count; i++)
        {
            //Generate patient payload
            String patientPayloadGenerated = generatePatientData(jsonTemplate,i);

            //Inserting generated payload into smileCDR
            Response response = insertPatientDataIntoSmile(patientPayloadGenerated);

            //Sample assertion
            String resourceID = getJsonPath(response, "id");
            System.out.println("Patient resource id is "+ resourceID);

            //Writing response to a file
            writeToFile(getGlobalValue("smileOutput"),response.asString());
        }
    }

    public static String generatePatientData(String jsonTemplate,int index) throws Exception {
        String patientJSON = FileUtils.readFileToString(new File(jsonTemplate));
        patientJSON = updateJson(patientJSON,index);
        return patientJSON;
    }


    private static String updateJson(String jsonTemplate,int index) throws Exception {
        String match = null,key= null;
        JsonParser jsonParser = new JsonParser();
        JsonObject jsonObject = jsonParser.parse(jsonTemplate).getAsJsonObject();
        // Iterate over key-value pairs using entrySet()
        for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
            String value = String.valueOf(entry.getValue());

            if (value.contains("<")) {
                Pattern pattern = Pattern.compile("<([^>]*)>");
                Matcher matcher = pattern.matcher(value);

                while (matcher.find()) {
                    match = matcher.group();
                    List<String> columnNames = getColumnNames();
                    for(String header: columnNames) {
                        if (header.equalsIgnoreCase(match)) {
                            List<String> columnValues = getValueFromCSV(match);
                            value = columnValues.get(index);
                            if (value.equalsIgnoreCase("null")) {
                                value = " ";
                            }
                            jsonTemplate = updateJson(jsonTemplate, match, value);
                            break;
                        }
                    }
                }
            }
        }

        return jsonTemplate;
    }




}

