import org.json.simple.JSONObject;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

public class readDataFromAzure extends utils {
    private static String jsonTemplate = getGlobalValue("jsonTemplate");
    public static void main(String[] args) throws IOException, SQLException, ClassNotFoundException {

        //Getting data from smileOutput file and storing as arraylist
        ArrayList<JSONObject> smileData= getResourceValues("smileOutput");

        //Get count of json to be generated by reading values having <> in template
        int count = getCount(jsonTemplate);

        for(int i = 0; i< count; i++){

            //Retrieving smileID and resourceType for each record
            String smileID= smileData.get(i).get("id").toString();
            String resourceName= smileData.get(i).get("resourceType").toString();

            //Creating sourceReference to fetch data from DB
            String sourceReference= resourceName+"/"+smileID;
//            String sourceReference= "Patient/26127256";

            //Fetch the corresponding azure ID From DB
        String azureID= getIDFromDB(sourceReference);
        System.out.println(azureID);

        //Reading patient data from azure
        response= readDataFromAzure(azureID);

        //Writing response to a file
        writeToFile(getGlobalValue("azureOutput"),response.asString());
        }

    }

}
